// DXCC entity lookup table
// Maps DXCC entity codes to { name, flag, continent }
// Source: ARRL DXCC List / AD1C CTY.DAT (December 2024)
// Converted from QRV/Shared/DXCCEntities.swift

const DXCC_ENTITIES = new Map([
  [1, { name: 'Canada', flag: '🇨🇦', continent: 'NA' }],
  [3, { name: 'Afghanistan', flag: '🇦🇫', continent: 'AS' }],
  [4, { name: 'Agalega & St. Brandon Islands', flag: '🇲🇺', continent: 'AF' }],
  [5, { name: 'Aland Islands', flag: '🇦🇽', continent: 'EU' }],
  [6, { name: 'Alaska', flag: '🇺🇸', continent: 'NA' }],
  [7, { name: 'Albania', flag: '🇦🇱', continent: 'EU' }],
  [9, { name: 'American Samoa', flag: '🇦🇸', continent: 'OC' }],
  [10, { name: 'Amsterdam & St. Paul Islands', flag: '🇹🇫', continent: 'AF' }],
  [11, { name: 'Andaman & Nicobar Islands', flag: '🇮🇳', continent: 'AS' }],
  [12, { name: 'Anguilla', flag: '🇦🇮', continent: 'NA' }],
  [13, { name: 'Antarctica', flag: '🇦🇶', continent: 'AN' }],
  [14, { name: 'Armenia', flag: '🇦🇲', continent: 'AS' }],
  [15, { name: 'Asiatic Russia', flag: '🇷🇺', continent: 'AS' }],
  [16, { name: 'New Zealand Subantarctic Islands', flag: '🇳🇿', continent: 'OC' }],
  [17, { name: 'Aves Island', flag: '🇻🇪', continent: 'NA' }],
  [18, { name: 'Azerbaijan', flag: '🇦🇿', continent: 'AS' }],
  [20, { name: 'Baker & Howland Islands', flag: '🇺🇲', continent: 'OC' }],
  [21, { name: 'Balearic Islands', flag: '🇪🇸', continent: 'EU' }],
  [22, { name: 'Palau', flag: '🇵🇼', continent: 'OC' }],
  [24, { name: 'Bouvet', flag: '🇧🇻', continent: 'AF' }],
  [27, { name: 'Belarus', flag: '🇧🇾', continent: 'EU' }],
  [29, { name: 'Canary Islands', flag: '🇮🇨', continent: 'AF' }],
  [31, { name: 'Central Kiribati (British Phoenix Islands)', flag: '🇰🇮', continent: 'OC' }],
  [32, { name: 'Ceuta & Melilla', flag: '🇪🇸', continent: 'AF' }],
  [33, { name: 'Chagos Islands', flag: '🇮🇴', continent: 'AF' }],
  [34, { name: 'Chatham Islands', flag: '🇳🇿', continent: 'OC' }],
  [35, { name: 'Christmas Island', flag: '🇨🇽', continent: 'OC' }],
  [36, { name: 'Clipperton Island', flag: '🇨🇵', continent: 'NA' }],
  [37, { name: 'Cocos Island', flag: '🇨🇷', continent: 'NA' }],
  [38, { name: 'Cocos (Keeling) Islands', flag: '🇨🇨', continent: 'OC' }],
  [40, { name: 'Crete', flag: '🇬🇷', continent: 'EU' }],
  [41, { name: 'Crozet Island', flag: '🇹🇫', continent: 'AF' }],
  [43, { name: 'Desecheo Island', flag: '🇵🇷', continent: 'NA' }],
  [45, { name: 'Dodecanese', flag: '🇬🇷', continent: 'EU' }],
  [46, { name: 'East Malaysia', flag: '🇲🇾', continent: 'OC' }],
  [47, { name: 'Easter Island', flag: '🇨🇱', continent: 'SA' }],
  [48, { name: 'Eastern Kiribati (Line Islands)', flag: '🇰🇮', continent: 'OC' }],
  [49, { name: 'Equatorial Guinea', flag: '🇬🇶', continent: 'AF' }],
  [50, { name: 'Mexico', flag: '🇲🇽', continent: 'NA' }],
  [51, { name: 'Eritrea', flag: '🇪🇷', continent: 'AF' }],
  [52, { name: 'Estonia', flag: '🇪🇪', continent: 'EU' }],
  [53, { name: 'Ethiopia', flag: '🇪🇹', continent: 'AF' }],
  [54, { name: 'European Russia', flag: '🇷🇺', continent: 'EU' }],
  [56, { name: 'Fernando de Noronha', flag: '🇧🇷', continent: 'SA' }],
  [60, { name: 'Bahamas', flag: '🇧🇸', continent: 'NA' }],
  [61, { name: 'Franz Josef Land', flag: '🇷🇺', continent: 'EU' }],
  [62, { name: 'Barbados', flag: '🇧🇧', continent: 'NA' }],
  [63, { name: 'French Guiana', flag: '🇬🇫', continent: 'SA' }],
  [64, { name: 'Bermuda', flag: '🇧🇲', continent: 'NA' }],
  [65, { name: 'British Virgin Islands', flag: '🇻🇬', continent: 'NA' }],
  [66, { name: 'Belize', flag: '🇧🇿', continent: 'NA' }],
  [69, { name: 'Cayman Islands', flag: '🇰🇾', continent: 'NA' }],
  [70, { name: 'Cuba', flag: '🇨🇺', continent: 'NA' }],
  [71, { name: 'Galapagos Islands', flag: '🇪🇨', continent: 'SA' }],
  [72, { name: 'Dominican Republic', flag: '🇩🇴', continent: 'NA' }],
  [74, { name: 'El Salvador', flag: '🇸🇻', continent: 'NA' }],
  [75, { name: 'Georgia', flag: '🇬🇪', continent: 'AS' }],
  [76, { name: 'Guatemala', flag: '🇬🇹', continent: 'NA' }],
  [77, { name: 'Grenada', flag: '🇬🇩', continent: 'NA' }],
  [78, { name: 'Haiti', flag: '🇭🇹', continent: 'NA' }],
  [79, { name: 'Guadeloupe', flag: '🇬🇵', continent: 'NA' }],
  [80, { name: 'Honduras', flag: '🇭🇳', continent: 'NA' }],
  [82, { name: 'Jamaica', flag: '🇯🇲', continent: 'NA' }],
  [84, { name: 'Martinique', flag: '🇲🇶', continent: 'NA' }],
  [86, { name: 'Nicaragua', flag: '🇳🇮', continent: 'NA' }],
  [88, { name: 'Panama', flag: '🇵🇦', continent: 'NA' }],
  [89, { name: 'Turks & Caicos Islands', flag: '🇹🇨', continent: 'NA' }],
  [90, { name: 'Trinidad & Tobago', flag: '🇹🇹', continent: 'SA' }],
  [91, { name: 'Aruba', flag: '🇦🇼', continent: 'SA' }],
  [94, { name: 'Antigua & Barbuda', flag: '🇦🇬', continent: 'NA' }],
  [95, { name: 'Dominica', flag: '🇩🇲', continent: 'NA' }],
  [96, { name: 'Montserrat', flag: '🇲🇸', continent: 'NA' }],
  [97, { name: 'St. Lucia', flag: '🇱🇨', continent: 'NA' }],
  [98, { name: 'St. Vincent', flag: '🇻🇨', continent: 'NA' }],
  [99, { name: 'Glorioso Islands', flag: '🇹🇫', continent: 'AF' }],
  [100, { name: 'Argentina', flag: '🇦🇷', continent: 'SA' }],
  [103, { name: 'Guam', flag: '🇬🇺', continent: 'OC' }],
  [104, { name: 'Bolivia', flag: '🇧🇴', continent: 'SA' }],
  [105, { name: 'Guantanamo Bay', flag: '🇺🇸', continent: 'NA' }],
  [106, { name: 'Guernsey', flag: '🇬🇬', continent: 'EU' }],
  [107, { name: 'Guinea', flag: '🇬🇳', continent: 'AF' }],
  [108, { name: 'Brazil', flag: '🇧🇷', continent: 'SA' }],
  [109, { name: 'Guinea-Bissau', flag: '🇬🇼', continent: 'AF' }],
  [110, { name: 'Hawaii', flag: '🇺🇸', continent: 'OC' }],
  [111, { name: 'Heard Island', flag: '🇭🇲', continent: 'AF' }],
  [112, { name: 'Chile', flag: '🇨🇱', continent: 'SA' }],
  [114, { name: 'Isle of Man', flag: '🇮🇲', continent: 'EU' }],
  [116, { name: 'Colombia', flag: '🇨🇴', continent: 'SA' }],
  [117, { name: 'ITU HQ', flag: '🇺🇳', continent: 'EU' }],
  [118, { name: 'Jan Mayen', flag: '🇳🇴', continent: 'EU' }],
  [120, { name: 'Ecuador', flag: '🇪🇨', continent: 'SA' }],
  [122, { name: 'Jersey', flag: '🇯🇪', continent: 'EU' }],
  [123, { name: 'Johnston Island', flag: '🇺🇲', continent: 'OC' }],
  [124, { name: 'Juan de Nova, Europa', flag: '🇹🇫', continent: 'AF' }],
  [125, { name: 'Juan Fernandez Islands', flag: '🇨🇱', continent: 'SA' }],
  [126, { name: 'Kaliningrad', flag: '🇷🇺', continent: 'EU' }],
  [129, { name: 'Guyana', flag: '🇬🇾', continent: 'SA' }],
  [130, { name: 'Kazakhstan', flag: '🇰🇿', continent: 'AS' }],
  [131, { name: 'Kerguelen Islands', flag: '🇹🇫', continent: 'AF' }],
  [132, { name: 'Paraguay', flag: '🇵🇾', continent: 'SA' }],
  [133, { name: 'Kermadec Islands', flag: '🇳🇿', continent: 'OC' }],
  [135, { name: 'Kyrgyzstan', flag: '🇰🇬', continent: 'AS' }],
  [136, { name: 'Peru', flag: '🇵🇪', continent: 'SA' }],
  [137, { name: 'Republic of Korea', flag: '🇰🇷', continent: 'AS' }],
  [138, { name: 'Kure Island', flag: '🇺🇸', continent: 'OC' }],
  [140, { name: 'Suriname', flag: '🇸🇷', continent: 'SA' }],
  [141, { name: 'Falkland Islands', flag: '🇫🇰', continent: 'SA' }],
  [142, { name: 'Lakshadweep Islands', flag: '🇮🇳', continent: 'AS' }],
  [143, { name: 'Laos', flag: '🇱🇦', continent: 'AS' }],
  [144, { name: 'Uruguay', flag: '🇺🇾', continent: 'SA' }],
  [145, { name: 'Latvia', flag: '🇱🇻', continent: 'EU' }],
  [146, { name: 'Lithuania', flag: '🇱🇹', continent: 'EU' }],
  [147, { name: 'Lord Howe Island', flag: '🇦🇺', continent: 'OC' }],
  [148, { name: 'Venezuela', flag: '🇻🇪', continent: 'SA' }],
  [149, { name: 'Azores', flag: '🇵🇹', continent: 'EU' }],
  [150, { name: 'Australia', flag: '🇦🇺', continent: 'OC' }],
  [152, { name: 'Macao', flag: '🇲🇴', continent: 'AS' }],
  [153, { name: 'Macquarie Island', flag: '🇦🇺', continent: 'OC' }],
  [157, { name: 'Nauru', flag: '🇳🇷', continent: 'OC' }],
  [158, { name: 'Vanuatu', flag: '🇻🇺', continent: 'OC' }],
  [159, { name: 'Maldives', flag: '🇲🇻', continent: 'AF' }],
  [160, { name: 'Tonga', flag: '🇹🇴', continent: 'OC' }],
  [161, { name: 'Malpelo Island', flag: '🇨🇴', continent: 'SA' }],
  [162, { name: 'New Caledonia', flag: '🇳🇨', continent: 'OC' }],
  [163, { name: 'Papua New Guinea', flag: '🇵🇬', continent: 'OC' }],
  [165, { name: 'Mauritius', flag: '🇲🇺', continent: 'AF' }],
  [166, { name: 'Mariana Islands', flag: '🇲🇵', continent: 'OC' }],
  [167, { name: 'Market Reef', flag: '🇫🇮', continent: 'EU' }],
  [168, { name: 'Marshall Islands', flag: '🇲🇭', continent: 'OC' }],
  [169, { name: 'Mayotte', flag: '🇾🇹', continent: 'AF' }],
  [170, { name: 'New Zealand', flag: '🇳🇿', continent: 'OC' }],
  [171, { name: 'Mellish Reef', flag: '🇦🇺', continent: 'OC' }],
  [172, { name: 'Pitcairn Island', flag: '🇵🇳', continent: 'OC' }],
  [173, { name: 'Micronesia', flag: '🇫🇲', continent: 'OC' }],
  [174, { name: 'Midway Island', flag: '🇺🇲', continent: 'OC' }],
  [175, { name: 'French Polynesia', flag: '🇵🇫', continent: 'OC' }],
  [176, { name: 'Fiji', flag: '🇫🇯', continent: 'OC' }],
  [177, { name: 'Minami Torishima', flag: '🇯🇵', continent: 'OC' }],
  [179, { name: 'Moldova', flag: '🇲🇩', continent: 'EU' }],
  [180, { name: 'Mount Athos', flag: '🇬🇷', continent: 'EU' }],
  [181, { name: 'Mozambique', flag: '🇲🇿', continent: 'AF' }],
  [182, { name: 'Navassa Island', flag: '🇺🇸', continent: 'NA' }],
  [185, { name: 'Solomon Islands', flag: '🇸🇧', continent: 'OC' }],
  [187, { name: 'Niger', flag: '🇳🇪', continent: 'AF' }],
  [188, { name: 'Niue', flag: '🇳🇺', continent: 'OC' }],
  [189, { name: 'Norfolk Island', flag: '🇳🇫', continent: 'OC' }],
  [190, { name: 'Samoa', flag: '🇼🇸', continent: 'OC' }],
  [191, { name: 'North Cook Islands', flag: '🇨🇰', continent: 'OC' }],
  [192, { name: 'Ogasawara', flag: '🇯🇵', continent: 'AS' }],
  [195, { name: 'Annobon Island', flag: '🇬🇶', continent: 'AF' }],
  [197, { name: 'Palmyra & Jarvis Islands', flag: '🇺🇲', continent: 'OC' }],
  [199, { name: 'Peter 1 Island', flag: '🇳🇴', continent: 'AN' }],
  [201, { name: 'Prince Edward & Marion Islands', flag: '🇿🇦', continent: 'AF' }],
  [202, { name: 'Puerto Rico', flag: '🇵🇷', continent: 'NA' }],
  [203, { name: 'Andorra', flag: '🇦🇩', continent: 'EU' }],
  [204, { name: 'Revillagigedo', flag: '🇲🇽', continent: 'NA' }],
  [205, { name: 'Ascension Island', flag: '🇦🇨', continent: 'AF' }],
  [206, { name: 'Austria', flag: '🇦🇹', continent: 'EU' }],
  [207, { name: 'Rodrigues Island', flag: '🇲🇺', continent: 'AF' }],
  [209, { name: 'Belgium', flag: '🇧🇪', continent: 'EU' }],
  [211, { name: 'Sable Island', flag: '🇨🇦', continent: 'NA' }],
  [212, { name: 'Bulgaria', flag: '🇧🇬', continent: 'EU' }],
  [213, { name: 'Saint Martin', flag: '🇲🇫', continent: 'NA' }],
  [214, { name: 'Corsica', flag: '🇫🇷', continent: 'EU' }],
  [215, { name: 'Cyprus', flag: '🇨🇾', continent: 'AS' }],
  [216, { name: 'San Andres & Providencia', flag: '🇨🇴', continent: 'NA' }],
  [217, { name: 'San Felix & San Ambrosio', flag: '🇨🇱', continent: 'SA' }],
  [219, { name: 'Sao Tome & Principe', flag: '🇸🇹', continent: 'AF' }],
  [221, { name: 'Denmark', flag: '🇩🇰', continent: 'EU' }],
  [222, { name: 'Faroe Islands', flag: '🇫🇴', continent: 'EU' }],
  [223, { name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', continent: 'EU' }],
  [224, { name: 'Finland', flag: '🇫🇮', continent: 'EU' }],
  [225, { name: 'Sardinia', flag: '🇮🇹', continent: 'EU' }],
  [227, { name: 'France', flag: '🇫🇷', continent: 'EU' }],
  [230, { name: 'Federal Republic of Germany', flag: '🇩🇪', continent: 'EU' }],
  [232, { name: 'Somalia', flag: '🇸🇴', continent: 'AF' }],
  [233, { name: 'Gibraltar', flag: '🇬🇮', continent: 'EU' }],
  [234, { name: 'South Cook Islands', flag: '🇨🇰', continent: 'OC' }],
  [235, { name: 'South Georgia Island', flag: '🇬🇸', continent: 'SA' }],
  [236, { name: 'Greece', flag: '🇬🇷', continent: 'EU' }],
  [237, { name: 'Greenland', flag: '🇬🇱', continent: 'NA' }],
  [238, { name: 'South Orkney Islands', flag: '🇬🇸', continent: 'SA' }],
  [239, { name: 'Hungary', flag: '🇭🇺', continent: 'EU' }],
  [240, { name: 'South Sandwich Islands', flag: '🇬🇸', continent: 'SA' }],
  [241, { name: 'South Shetland Islands', flag: '🇦🇶', continent: 'SA' }],
  [242, { name: 'Iceland', flag: '🇮🇸', continent: 'EU' }],
  [245, { name: 'Ireland', flag: '🇮🇪', continent: 'EU' }],
  [246, { name: 'Sovereign Military Order of Malta', flag: '🇻🇦', continent: 'EU' }],
  [247, { name: 'Spratly Islands', flag: '\uD83C\uDFDD\uFE0F', continent: 'AS' }],
  [248, { name: 'Italy', flag: '🇮🇹', continent: 'EU' }],
  [249, { name: 'St. Kitts & Nevis', flag: '🇰🇳', continent: 'NA' }],
  [250, { name: 'St. Helena', flag: '🇸🇭', continent: 'AF' }],
  [251, { name: 'Liechtenstein', flag: '🇱🇮', continent: 'EU' }],
  [252, { name: 'St. Paul Island', flag: '🇨🇦', continent: 'NA' }],
  [253, { name: 'St. Peter & St. Paul Rocks', flag: '🇧🇷', continent: 'SA' }],
  [254, { name: 'Luxembourg', flag: '🇱🇺', continent: 'EU' }],
  [256, { name: 'Madeira Islands', flag: '🇵🇹', continent: 'AF' }],
  [257, { name: 'Malta', flag: '🇲🇹', continent: 'EU' }],
  [259, { name: 'Svalbard', flag: '🇳🇴', continent: 'EU' }],
  [260, { name: 'Monaco', flag: '🇲🇨', continent: 'EU' }],
  [262, { name: 'Tajikistan', flag: '🇹🇯', continent: 'AS' }],
  [263, { name: 'Netherlands', flag: '🇳🇱', continent: 'EU' }],
  [265, { name: 'Northern Ireland', flag: '🇬🇧', continent: 'EU' }],
  [266, { name: 'Norway', flag: '🇳🇴', continent: 'EU' }],
  [269, { name: 'Poland', flag: '🇵🇱', continent: 'EU' }],
  [270, { name: 'Tokelau Islands', flag: '🇹🇰', continent: 'OC' }],
  [272, { name: 'Portugal', flag: '🇵🇹', continent: 'EU' }],
  [273, { name: 'Trindade & Martim Vaz Islands', flag: '🇧🇷', continent: 'SA' }],
  [274, { name: 'Tristan da Cunha & Gough Islands', flag: '🇸🇭', continent: 'AF' }],
  [275, { name: 'Romania', flag: '🇷🇴', continent: 'EU' }],
  [276, { name: 'Tromelin Island', flag: '🇹🇫', continent: 'AF' }],
  [277, { name: 'St. Pierre & Miquelon', flag: '🇵🇲', continent: 'NA' }],
  [278, { name: 'San Marino', flag: '🇸🇲', continent: 'EU' }],
  [279, { name: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', continent: 'EU' }],
  [280, { name: 'Turkmenistan', flag: '🇹🇲', continent: 'AS' }],
  [281, { name: 'Spain', flag: '🇪🇸', continent: 'EU' }],
  [282, { name: 'Tuvalu', flag: '🇹🇻', continent: 'OC' }],
  [283, { name: 'UK Sovereign Base Areas on Cyprus', flag: '🇬🇧', continent: 'AS' }],
  [284, { name: 'Sweden', flag: '🇸🇪', continent: 'EU' }],
  [285, { name: 'Virgin Islands', flag: '🇻🇮', continent: 'NA' }],
  [286, { name: 'Uganda', flag: '🇺🇬', continent: 'AF' }],
  [287, { name: 'Switzerland', flag: '🇨🇭', continent: 'EU' }],
  [288, { name: 'Ukraine', flag: '🇺🇦', continent: 'EU' }],
  [289, { name: 'United Nations HQ', flag: '🇺🇳', continent: 'NA' }],
  [291, { name: 'United States of America', flag: '🇺🇸', continent: 'NA' }],
  [292, { name: 'Uzbekistan', flag: '🇺🇿', continent: 'AS' }],
  [293, { name: 'Vietnam', flag: '🇻🇳', continent: 'AS' }],
  [294, { name: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', continent: 'EU' }],
  [295, { name: 'Vatican City', flag: '🇻🇦', continent: 'EU' }],
  [296, { name: 'Serbia', flag: '🇷🇸', continent: 'EU' }],
  [297, { name: 'Wake Island', flag: '🇺🇲', continent: 'OC' }],
  [298, { name: 'Wallis & Futuna Islands', flag: '🇼🇫', continent: 'OC' }],
  [299, { name: 'West Malaysia', flag: '🇲🇾', continent: 'AS' }],
  [301, { name: 'Western Kiribati (Gilbert Islands)', flag: '🇰🇮', continent: 'OC' }],
  [302, { name: 'Western Sahara', flag: '🇪🇭', continent: 'AF' }],
  [303, { name: 'Willis Island', flag: '🇦🇺', continent: 'OC' }],
  [304, { name: 'Bahrain', flag: '🇧🇭', continent: 'AS' }],
  [305, { name: 'Bangladesh', flag: '🇧🇩', continent: 'AS' }],
  [306, { name: 'Bhutan', flag: '🇧🇹', continent: 'AS' }],
  [308, { name: 'Costa Rica', flag: '🇨🇷', continent: 'NA' }],
  [309, { name: 'Myanmar', flag: '🇲🇲', continent: 'AS' }],
  [312, { name: 'Cambodia', flag: '🇰🇭', continent: 'AS' }],
  [315, { name: 'Sri Lanka', flag: '🇱🇰', continent: 'AS' }],
  [318, { name: 'China', flag: '🇨🇳', continent: 'AS' }],
  [321, { name: 'Hong Kong', flag: '🇭🇰', continent: 'AS' }],
  [324, { name: 'India', flag: '🇮🇳', continent: 'AS' }],
  [327, { name: 'Indonesia', flag: '🇮🇩', continent: 'OC' }],
  [330, { name: 'Iran', flag: '🇮🇷', continent: 'AS' }],
  [333, { name: 'Iraq', flag: '🇮🇶', continent: 'AS' }],
  [336, { name: 'Israel', flag: '🇮🇱', continent: 'AS' }],
  [339, { name: 'Japan', flag: '🇯🇵', continent: 'AS' }],
  [342, { name: 'Jordan', flag: '🇯🇴', continent: 'AS' }],
  [344, { name: "Democratic People's Republic of Korea", flag: '🇰🇵', continent: 'AS' }],
  [345, { name: 'Brunei Darussalam', flag: '🇧🇳', continent: 'OC' }],
  [348, { name: 'Kuwait', flag: '🇰🇼', continent: 'AS' }],
  [354, { name: 'Lebanon', flag: '🇱🇧', continent: 'AS' }],
  [363, { name: 'Mongolia', flag: '🇲🇳', continent: 'AS' }],
  [369, { name: 'Nepal', flag: '🇳🇵', continent: 'AS' }],
  [370, { name: 'Oman', flag: '🇴🇲', continent: 'AS' }],
  [372, { name: 'Pakistan', flag: '🇵🇰', continent: 'AS' }],
  [375, { name: 'Philippines', flag: '🇵🇭', continent: 'OC' }],
  [376, { name: 'Qatar', flag: '🇶🇦', continent: 'AS' }],
  [378, { name: 'Saudi Arabia', flag: '🇸🇦', continent: 'AS' }],
  [379, { name: 'Seychelles', flag: '🇸🇨', continent: 'AF' }],
  [381, { name: 'Singapore', flag: '🇸🇬', continent: 'AS' }],
  [382, { name: 'Djibouti', flag: '🇩🇯', continent: 'AF' }],
  [384, { name: 'Syria', flag: '🇸🇾', continent: 'AS' }],
  [386, { name: 'Taiwan', flag: '🇹🇼', continent: 'AS' }],
  [387, { name: 'Thailand', flag: '🇹🇭', continent: 'AS' }],
  [390, { name: 'Turkey', flag: '🇹🇷', continent: 'EU' }],
  [391, { name: 'United Arab Emirates', flag: '🇦🇪', continent: 'AS' }],
  [400, { name: 'Algeria', flag: '🇩🇿', continent: 'AF' }],
  [401, { name: 'Angola', flag: '🇦🇴', continent: 'AF' }],
  [402, { name: 'Botswana', flag: '🇧🇼', continent: 'AF' }],
  [404, { name: 'Burundi', flag: '🇧🇮', continent: 'AF' }],
  [406, { name: 'Cameroon', flag: '🇨🇲', continent: 'AF' }],
  [408, { name: 'Central African Republic', flag: '🇨🇫', continent: 'AF' }],
  [409, { name: 'Cape Verde', flag: '🇨🇻', continent: 'AF' }],
  [410, { name: 'Chad', flag: '🇹🇩', continent: 'AF' }],
  [411, { name: 'Comoros', flag: '🇰🇲', continent: 'AF' }],
  [412, { name: 'Congo (Republic of the)', flag: '🇨🇬', continent: 'AF' }],
  [414, { name: 'Democratic Republic of the Congo', flag: '🇨🇩', continent: 'AF' }],
  [416, { name: 'Benin', flag: '🇧🇯', continent: 'AF' }],
  [420, { name: 'Gabon', flag: '🇬🇦', continent: 'AF' }],
  [422, { name: 'The Gambia', flag: '🇬🇲', continent: 'AF' }],
  [424, { name: 'Ghana', flag: '🇬🇭', continent: 'AF' }],
  [428, { name: "Cote d'Ivoire", flag: '🇨🇮', continent: 'AF' }],
  [430, { name: 'Kenya', flag: '🇰🇪', continent: 'AF' }],
  [432, { name: 'Lesotho', flag: '🇱🇸', continent: 'AF' }],
  [434, { name: 'Liberia', flag: '🇱🇷', continent: 'AF' }],
  [436, { name: 'Libya', flag: '🇱🇾', continent: 'AF' }],
  [438, { name: 'Madagascar', flag: '🇲🇬', continent: 'AF' }],
  [440, { name: 'Malawi', flag: '🇲🇼', continent: 'AF' }],
  [442, { name: 'Mali', flag: '🇲🇱', continent: 'AF' }],
  [444, { name: 'Mauritania', flag: '🇲🇷', continent: 'AF' }],
  [446, { name: 'Morocco', flag: '🇲🇦', continent: 'AF' }],
  [450, { name: 'Nigeria', flag: '🇳🇬', continent: 'AF' }],
  [452, { name: 'Zimbabwe', flag: '🇿🇼', continent: 'AF' }],
  [453, { name: 'Reunion Island', flag: '🇷🇪', continent: 'AF' }],
  [454, { name: 'Rwanda', flag: '🇷🇼', continent: 'AF' }],
  [456, { name: 'Senegal', flag: '🇸🇳', continent: 'AF' }],
  [458, { name: 'Sierra Leone', flag: '🇸🇱', continent: 'AF' }],
  [460, { name: 'Rotuma Island', flag: '🇫🇯', continent: 'OC' }],
  [462, { name: 'South Africa', flag: '🇿🇦', continent: 'AF' }],
  [464, { name: 'Namibia', flag: '🇳🇦', continent: 'AF' }],
  [466, { name: 'Sudan', flag: '🇸🇩', continent: 'AF' }],
  [468, { name: 'Kingdom of Eswatini', flag: '🇸🇿', continent: 'AF' }],
  [470, { name: 'Tanzania', flag: '🇹🇿', continent: 'AF' }],
  [474, { name: 'Tunisia', flag: '🇹🇳', continent: 'AF' }],
  [478, { name: 'Egypt', flag: '🇪🇬', continent: 'AF' }],
  [480, { name: 'Burkina Faso', flag: '🇧🇫', continent: 'AF' }],
  [482, { name: 'Zambia', flag: '🇿🇲', continent: 'AF' }],
  [483, { name: 'Togo', flag: '🇹🇬', continent: 'AF' }],
  [489, { name: 'Conway Reef', flag: '\uD83C\uDFDD\uFE0F', continent: 'OC' }],
  [490, { name: 'Banaba Island (Ocean Island)', flag: '🇰🇮', continent: 'OC' }],
  [492, { name: 'Yemen', flag: '🇾🇪', continent: 'AS' }],
  [497, { name: 'Croatia', flag: '🇭🇷', continent: 'EU' }],
  [499, { name: 'Slovenia', flag: '🇸🇮', continent: 'EU' }],
  [501, { name: 'Bosnia-Herzegovina', flag: '🇧🇦', continent: 'EU' }],
  [502, { name: 'North Macedonia', flag: '🇲🇰', continent: 'EU' }],
  [503, { name: 'Czech Republic', flag: '🇨🇿', continent: 'EU' }],
  [504, { name: 'Slovak Republic', flag: '🇸🇰', continent: 'EU' }],
  [505, { name: 'Pratas Island', flag: '🇹🇼', continent: 'AS' }],
  [506, { name: 'Scarborough Reef', flag: '\uD83C\uDFDD\uFE0F', continent: 'AS' }],
  [507, { name: 'Temotu Province', flag: '🇸🇧', continent: 'OC' }],
  [508, { name: 'Austral Islands', flag: '🇵🇫', continent: 'OC' }],
  [509, { name: 'Marquesas Islands', flag: '🇵🇫', continent: 'OC' }],
  [510, { name: 'Palestine', flag: '🇵🇸', continent: 'AS' }],
  [511, { name: 'Timor-Leste', flag: '🇹🇱', continent: 'OC' }],
  [512, { name: 'Chesterfield Islands', flag: '🇳🇨', continent: 'OC' }],
  [513, { name: 'Ducie Island', flag: '🇵🇳', continent: 'OC' }],
  [514, { name: 'Montenegro', flag: '🇲🇪', continent: 'EU' }],
  [515, { name: 'Swains Island', flag: '🇺🇲', continent: 'OC' }],
  [516, { name: 'Saint Barthelemy', flag: '🇧🇱', continent: 'NA' }],
  [517, { name: 'Curacao', flag: '🇨🇼', continent: 'SA' }],
  [518, { name: 'Sint Maarten', flag: '🇸🇽', continent: 'NA' }],
  [519, { name: 'Saba & St. Eustatius', flag: '🇧🇶', continent: 'NA' }],
  [520, { name: 'Bonaire', flag: '🇧🇶', continent: 'SA' }],
  [521, { name: 'South Sudan (Republic of)', flag: '🇸🇸', continent: 'AF' }],
  [522, { name: 'Republic of Kosovo', flag: '🇽🇰', continent: 'EU' }],
]);

export function lookupDXCC(code) {
  const num = typeof code === 'string' ? parseInt(code, 10) : code;
  if (!num || isNaN(num)) return null;
  return DXCC_ENTITIES.get(num) || null;
}
